# Generated by Django 5.1.7 on 2025-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Adiministrador'), ('colaborador', 'Colaborador')], max_length=20),
        ),
    ]
