# Generated by Django 5.1.7 on 2025-04-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0005_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('colaborador', 'Colaborador')], max_length=20),
        ),
    ]
