# Generated by Django 5.1.7 on 2025-04-24 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0007_indicacao_colaborador_contratacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apadrinhado',
            name='apadrinhado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_apadrinhados', to=settings.AUTH_USER_MODEL),
        ),
    ]
